### ISSUE TITLE
Feature Request(s): Avatar / Button | Shadows

### ISSUE THREAD

**Issue by jjjonesjr33** [techno-tim/littlelink-server#191]
## Shadows make this so much more enjoyable to look at than just flat buttons.

Tested and working by overriding CSS via elements and directly overriding the docker css. ( However this will break for me when new buttons are added unless I update the css manually after each update.)
### Shadow effect 
 - Gives the avatar / buttons a more pop out and stylish look.
`box-shadow: 5px 5px 5px #0000006e;`

![image](https://user-images.githubusercontent.com/29973406/181639922-538cf06c-5cd2-4c23-b61a-cde90e8f3195.png)

## Avatar code: 
 - `/usr/src/app/build/public/static/css/client.f553e0c7.css` <<< tested on multiple instances and this seems to be the same per each docker/container for the avatar css.
``` css
.avatar{vertical-align:middle;width:128px;height:128px;box-shadow: 5px 5px 5px #0000006e;border-radius:50%}
```

## Button code: 
 - `/usr/src/app/build/public/css/brands.css`
 
Snippet code to override for `.button` - This is the only part the needs to be modified for it to apply to all buttons
``` css
.button,button{display:inline-block;text-decoration:none;height:48px;box-shadow: 5px 5px 5px #0000006e;text-align:center;vertical-align:middle;font-size:18px;width:300px;font-weight:700;line-height:48px;letter-spacing:.1px;white-space:wrap;border-radius:8px;cursor:pointer}
```
