### ISSUE TITLE
[BUG REPORT] Unable to remove Github link to https://github.com/timothystewart6

### ISSUE THREAD

**Issue by natehouk** [techno-tim/littlelink-server#301]
### Buttons Relation

Github

### Bug Description

If I comment out the Github line in my values.yaml then a default Github button appears linking to https://github.com/timothystewart6

For all other buttons, by not providing the env variable, the button doesn't appear. For some reason, when I don't provide the env variable, the variable GITHUB still gets exported into the docker container with the value https://github.com/timothystewart6

Why is the env variable GITHUB getting a default value? Where is this coming from? I have searched the code and don't see anything that would indicate there is a default env variable for GITHUB.

However, if I set the GITHUB variable in values.yaml to "", then the button disappears. This is the only button where I need to set the variable to "".

Here are my values.yaml...

BROKEN
```
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/techno-tim/littlelink-server
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [littlelink-server documentation](https://github.com/techno-tim/littlelink-server).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Amsterdam
  META_TITLE: The Muttonchop Murderer
  META_DESCRIPTION: The Muttonchop Murderer Linktree
  META_AUTHOR: The Muttonchop Murderer
  THEME: Dark
  FAVICON_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
  AVATAR_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
  AVATAR_2X_URL: https://pbs.twimcg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
  AVATAR_ALT: The Muttonchop Murderer Profile Pic
  NAME: The Muttonchop Murderer
  BIO: Hey! Just a place where you can connect with me!
  # GITHUB:
  # TWITTER: https://twitter.com/TechnoTimLive
  INSTAGRAM: https://instagram.com/epsilonrecords
  YOUTUBE: https://youtube.com/epsilonrecords
  TWITCH: https://twitch.tv/epsilonrecords
  DISCORD: https://discord.gg/epsilonrecords
  TIKTOK: https://www.tiktok.com/@epsilonrecords
  # KIT: https://kit.co/TechnoTim
  FACEBOOK: https://facebook.com/epsilonrecords.nl
  # FACEBOOK_MESSENGER: https://facebook.com
  LINKED_IN: https://www.linkedin.com/company/epsilon-records/
  # PRODUCT_HUNT: https://www.producthunt.com/
  SNAPCHAT: http://snapchat.com/add/epsilonrecords
  SPOTIFY: https://open.spotify.com/playlist/3V3NcVTRCHomITtmWLb86I?si=d6dc137cf0f740bf
  REDDIT: https://www.reddit.com/r/EpsilonRecords/
  # MEDIUM: https://medium.com
  PINTEREST: https://pinterest.com/epsilonrecords/
  EMAIL: nate@epsilonrecords.com
  # EMAIL_ALT: you@example.com
  SOUND_CLOUD: https://soundcloud.com/epsilonrecords
  MASTODON: https://mastodonmusic.social/@epsilonrecords
  PATREON: https://patreon.com/epsilonrecords
  LASTFM: https://last.fm/user/natehouk
  PRIVATEBIN: https://paste.epsilonrecords.nl
  VENMO: http://venmo.com/epsilonrecords
  # FIGMA: https://figma.com
  # TELEGRAM: https://telegram.org/
  # TUMBLR: https://www.tumblr.com/
  # STEAM: https://steamcommunity.com/
  # VIMEO: https://vimeo.com/
  # WORDPRESS: https://wordpress.com/
  # GOODREADS: https://www.goodreads.com/
  # SKOOB: https://www.skoob.com.br/
  FOOTER: Thanks for stopping by!

#  -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
```

WORKS
```
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/techno-tim/littlelink-server
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [littlelink-server documentation](https://github.com/techno-tim/littlelink-server).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Amsterdam
  META_TITLE: The Muttonchop Murderer
  META_DESCRIPTION: The Muttonchop Murderer Linktree
  META_AUTHOR: The Muttonchop Murderer
  THEME: Dark
  FAVICON_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
  AVATAR_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
  AVATAR_2X_URL: https://pbs.twimcg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
  AVATAR_ALT: The Muttonchop Murderer Profile Pic
  NAME: The Muttonchop Murderer
  BIO: Hey! Just a place where you can connect with me!
  GITHUB:
  # TWITTER: https://twitter.com/TechnoTimLive
  INSTAGRAM: https://instagram.com/epsilonrecords
  YOUTUBE: https://youtube.com/epsilonrecords
  TWITCH: https://twitch.tv/epsilonrecords
  DISCORD: https://discord.gg/epsilonrecords
  TIKTOK: https://www.tiktok.com/@epsilonrecords
  # KIT: https://kit.co/TechnoTim
  FACEBOOK: https://facebook.com/epsilonrecords.nl
  # FACEBOOK_MESSENGER: https://facebook.com
  LINKED_IN: https://www.linkedin.com/company/epsilon-records/
  # PRODUCT_HUNT: https://www.producthunt.com/
  SNAPCHAT: http://snapchat.com/add/epsilonrecords
  SPOTIFY: https://open.spotify.com/playlist/3V3NcVTRCHomITtmWLb86I?si=d6dc137cf0f740bf
  REDDIT: https://www.reddit.com/r/EpsilonRecords/
  # MEDIUM: https://medium.com
  PINTEREST: https://pinterest.com/epsilonrecords/
  EMAIL: nate@epsilonrecords.com
  # EMAIL_ALT: you@example.com
  SOUND_CLOUD: https://soundcloud.com/epsilonrecords
  MASTODON: https://mastodonmusic.social/@epsilonrecords
  PATREON: https://patreon.com/epsilonrecords
  LASTFM: https://last.fm/user/natehouk
  PRIVATEBIN: https://paste.epsilonrecords.nl
  VENMO: http://venmo.com/epsilonrecords
  # FIGMA: https://figma.com
  # TELEGRAM: https://telegram.org/
  # TUMBLR: https://www.tumblr.com/
  # STEAM: https://steamcommunity.com/
  # VIMEO: https://vimeo.com/
  # WORDPRESS: https://wordpress.com/
  # GOODREADS: https://www.goodreads.com/
  # SKOOB: https://www.skoob.com.br/
  FOOTER: Thanks for stopping by!

#  -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
```

Why is this fake GITHUB="" required for only Github and none of the other buttons?

### Expected Result

No Github button appears if I comment out the Github env variable. Expect the env variable GITHUB to not be set.
