### ISSUE TITLE
Custom website URL not appearing

### ISSUE THREAD

**Issue by samip5** [techno-tim/littlelink-server#77]
Hi,

I tried to get the custom website url thing working, but I'm unable to. I don't know if I'm doing it wrong or what's the issue.
Keep in mind, I'm using this on Kubernetes, via the https://github.com/k8s-at-home/charts/tree/master/charts/stable/littlelink-server chart, but should not matter.

Ideas why my custom button does not appear?
Link tree is at https://samip.dev.

```yaml
env:
      TZ: "Europe/Helsinki"
      META_TITLE: Skyler Mäntysaari
      META_DESCRIPTION: Skyler M Link Page
      META_AUTHOR: Skyler Mäntysaari
      THEME: Dark
      FAVICON_URL: https://avatars.githubusercontent.com/u/1703002?v=4
      AVATAR_URL: https://avatars.githubusercontent.com/u/1703002?v=4
      AVATAR_2X_URL: https://avatars.githubusercontent.com/u/1703002?v=4
      AVATAR_ALT: Skyler Mäntysaari
      NAME: Skyler Mäntysaari
      BIO: Hi there traveler! You have managed to find the link index of mine. Good job! :)
      BUTTON_ORDER: GITHUB,GITLAB,GITEA,LINKED_IN,TELEGRAM
      GITHUB: https://github.com/samip5
      GITLAB: https://gitlab.com/samip5
      GITEA: https://git.samip.fi
      CUSTOM_BUTTON_TEXT: Donate!
      CUSTOM_BUTTON_NAME: Donations
      CUSTOM_BUTTON_URL: https://liberapay.com/samip537/
      CUSTOM_BUTTON_ICON: fas fa-donate
      CUSTOM_BUTTON_COLOR: #ED2756
      BUTTON_TARGET: _blank
      LINKED_IN: https://linkedin.com/in/samip537
      TWITTER: https://twitter.com/mantysaaris
      TELEGRAM: https://t.me/samip537
      STEAM: https://steamcommunity.com/id/samip537
      FOOTER: Thank you for visiting. :)
```
